hibernate:
  cache:
    queries: false
    use_second_level_cache: false
    use_query_cache: false

grails:
  cors:
    enabled: true
    allowedOrigins:
      - "*"
    allowedMethods:
      - GET
      - POST
      - PUT
      - DELETE
      - OPTIONS
    allowedHeaders:
      - Authorization
      - Content-Type
      - X-Requested-With

  plugin:
    springsecurity:
      userLookup:
        userDomainClassName: 'CLI.User'
        authorityJoinClassName: 'CLI.UserRole'
      authority:
        className: 'CLI.Role'

      csrf:
        disabled: true

      securityConfigType: "InterceptUrlMap"
      rejectIfNoRule: false
      interceptUrlMap:
        - pattern: '/assets/**'
          access: [ 'permitAll' ]
        - pattern: '/api/**'
          access: [ 'permitAll' ]
        - pattern: '/**'
          access: [ 'IS_AUTHENTICATED_ANONYMOUSLY' ]

      filterChain:
        chainMap:
          - pattern: '/assets/**'
            filters: 'none'
          - pattern: '/api/**'
            filters: 'JOINED_FILTERS,-exceptionTranslationFilter,-authenticationProcessingFilter,-securityContextPersistenceFilter,-rememberMeAuthenticationFilter'
          - pattern: '/**'
            filters: 'JOINED_FILTERS'

  controllers:
    upload:
      maxFileSize: 20MB
      maxRequestSize: 20MB

spring:
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

# =========================
# DataSource (MySQL / H2)
# =========================
dataSource:
  pooled: true
  jmxExport: true
  driverClassName: com.mysql.cj.jdbc.Driver
  dialect: org.hibernate.dialect.MySQL8Dialect
  username: root
  password: sadeel123456

environments:
  development:
    dataSource:
      dbCreate: update
      url: jdbc:mysql://127.0.0.1:3306/university?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&useUnicode=true&characterEncoding=utf8

  test:
    dataSource:
      dbCreate: update
      url: jdbc:h2:mem:testDb;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE

  production:
    dataSource:
      dbCreate: none
      url: jdbc:mysql://localhost:3306/university?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
      properties:
        jmxEnabled: true
        initialSize: 5
        maxActive: 50
        minIdle: 5
        maxIdle: 25
        maxWait: 10000
        maxAge: 600000
        timeBetweenEvictionRunsMillis: 5000
        minEvictableIdleTimeMillis: 60000
        validationQuery: SELECT 1
        validationQueryTimeout: 3
        validationInterval: 15000
        testOnBorrow: true
        testWhileIdle: true
        testOnReturn: false
        jdbcInterceptors: ConnectionState
        defaultTransactionIsolation: 2
